const instituts = [
  {
    institut_id: 1,
    label: 'Institut Français',
    adress1: '123 rue du Général Degaule',
    adress2: '',
    zipcode: '75000',
    city: 'paris',
    country_id: 76,
    email: 'contact@institut-france.com',
    siteweb: 'www.institut-france.fr',
    phone: '+33123456789',
    socialNetwork: {
      facebook: 'FbProfil',
      twitter: 'TwitProfil',
      instagram: 'InstaProfil',
      linkedin: 'LinkedProfil',
    },
    stripeId: 'acct_1KxRS8QxaIfpu4Sw',
    stripeActivated: true,
  },
  {
    institut_id: 2,
    label: 'Tenri Japanese School',
    adress1: '456bis Avenue Jules Brunet',
    adress2: 'Apt 15B - Bât 12',
    zipcode: '75000',
    city: 'paris',
    country_id: 75,
    email: 'contact@tenri.co.jp',
    siteweb: 'www.tenri.co.jp',
    phone: '+9874561230',
    socialNetwork: {
      facebook: 'FbProfil',
      twitter: 'TwitProfil',
      instagram: 'InstaProfil',
      linkedin: 'LinkedProfil',
    },
    stripeId: 'acct_1KxRS8QxaIfpu4Sw',
    stripeActivated: true,
  },
];
export default instituts;
